import React, { useState, useRef } from "react";
import "./App.css";
import Bookmark from "./Bookmark.jsx";

const App = () => {
  const audioRef = useRef(null);
    const [word, setWord] = useState("");
      const [dictionaryData, setDictionaryData] = useState(null);
        const [err, setErr] = useState("");
          const [isBookmarked, setIsBookmarked] = useState(false);
            const [isBookmarkedOpen, setIsBookmarkedOpen] = useState(false);
              const [bookmarks, setBookmarks] = useState([]);

                const toggleBookmark = () => {
                    if (!dictionaryData) return;
                        const word = dictionaryData.word;
                            const definition =
                                  dictionaryData.meanings[0]?.definitions[0]?.definition ||
                                        "No definition";

                                            let updatedBookmarks;
                                                const isAlreadyBookmarked =
                                                  bookmarks.filter(
                                                      (bookmark) => bookmark.word.toLowerCase() === word.toLowerCase()
                                                        ).length > 0;

                                                            if (isAlreadyBookmarked) {
                                                                  updatedBookmarks = bookmarks.filter(
                                                                        (bookmark) => bookmark.word.toLowerCase() !== word.toLowerCase()
                                                                            );
                                                                                } else {
                                                                                      updatedBookmarks = [...bookmarks, { word, definition }];    
                                                                                          }

                                                                                              
                                                                                                  
                                                                                                      setBookmarks(updatedBookmarks);
                                                                                                          setIsBookmarked(!isAlreadyBookmarked);
                                                                                                            };

                                                                                                              const handleClick = () => {
                                                                                                                  if (!word.trim()) {
                                                                                                                        setErr("Please enter a word.");
                                                                                                                              setDictionaryData(null);
                                                                                                                                    return;
                                                                                                                                        }
                                                                                                                                            setIsBookmarked(false);
                                                                                                                                                fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${word}`)
                                                                                                                                                      .then((response) => {
                                                                                                                                                              if (!response.ok) {
                                                                                                                                                                        throw new Error("Word not found!");
                                                                                                                                                                                }
                                                                                                                                                                                        return response.json();
                                                                                                                                                                                              })
                                                                                                                                                                                                    .then((data) => {
                                                                                                                                                                                                            setDictionaryData(data[0]);
                                                                                                                                                                                                                    setErr(null);
                                                                                                                                                                                                                          })
                                                                                                                                                                                                                                .catch((error) => {
                                                                                                                                                                                                                                        setErr(error.message);
                                                                                                                                                                                                                                                setDictionaryData(null);
                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                          const playAudio = () => {
                                                                                                                                                                                                                                                              if (audioRef.current) {
                                                                                                                                                                                                                                                                    audioRef.current.play();
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                            const handleBookmarkPage = () => {
                                                                                                                                                                                                                                                                                setIsBookmarkedOpen(!isBookmarkedOpen);
                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                              {isBookmarkedOpen ? (
                                                                                                                                                                                                                                                                                                      <Bookmark
                                                                                                                                                                                                                                                                                                                setIsBookmarkedOpen={setIsBookmarkedOpen}
                                                                                                                                                                                                                                                                                                                          bookmarks={bookmarks}
                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                <div className="main">
                                                                                                                                                                                                                                                                                                                                                          <div className="view-bookmarks-div">
                                                                                                                                                                                                                                                                                                                                                                      <h3>(Not sponsored)</h3>
                                                                                                                                                                                                                                                                                                                                                                                  <button className="view-bookmarks" onClick={handleBookmarkPage}>
                                                                                                                                                                                                                                                                                                                                                                                                View Bookmarks
                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                <h1 className="title">Word Finder</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="description">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      Type a word into the box below to find its definition or related
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  words.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="input-div">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={word}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setWord(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Enter a word"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={handleClick}>Search</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {(err || dictionaryData) && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="show-data">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {err && <p className="error">{err}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {dictionaryData && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="audio-div">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h1>{dictionaryData.word}</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="icons_div">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="material-icons"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ cursor: "pointer", fontSize: "22px" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={playAudio}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    volume_up
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="material-icons"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: "22px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: isBookmarked ? "red" : "#777",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={toggleBookmark}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            bookmark
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>{dictionaryData.phonetic}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {dictionaryData.origin || "Origin not available."}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="noun">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {dictionaryData.meanings[0].partOfSpeech}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="noun_description">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {dictionaryData.meanings[0].definitions[0].definition}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {dictionaryData.phonetics[0]?.audio && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <audio ref={audioRef} src={dictionaryData.phonetics[0].audio} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default App;